name: Build da game
run-name: ${{ github.actor }} game deved and wants to build 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - run: |
          ls -la
          echo ============================================
          ls -la .github
          echo ============================================
          ls -la .github
          echo ============================================
          ls -la .github/actions
          echo ============================================
          ls -la .github/actions/build
          echo ============================================
          ls -la .github/actions/install
          

      - name: install Godot
        uses: ./.github/actions/install/action.yml
        with:
          install-templates: true
          godot-version: 4.4.1
        id: install_godot

      - name: build Game
        uses: ./.github/actions/build/action.yml
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
