name: Build da game
run-name: ${{ github.actor }} game deved and wants to build 🚀
on: [push]
jobs:
  Build-Godot-Game:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: install Godot
        uses: ./.github/actions/install
        with:
          install-templates: true
          godot-version: 4.4.1
        id: install_godot

      - name: build Game
        uses: ./.github/actions/build
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
