name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: install Godot
        uses: ./.github/actions/install
        with:
          install-templates: true
          godot-version: 4.4.1
        id: install_godot

      - name: build Game
        uses: ./.github/actions/build
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
